"""Operations that must happen before a tenant is known (AC-1).

Signup has a genuine ordering problem: **resolving which tenant an email domain
belongs to is itself a cross-tenant read**, and it happens before any
``TenantContext`` can exist. So does the per-IP rate limit, whose whole job is to
count attempts that get *refused* — attempts that by definition have no tenant.

Why this is not ``SystemRepository``: that class audits every call, which is
right for platform operations and wrong here. Signup is a public, unauthenticated
endpoint; auditing every hit would fill ``audit_log`` with noise generated by
anyone who can reach the login page, and drown the cross-tenant reads that
actually matter.

So it is a second, separately named path with a much narrower contract:

* **two data operations only**, both listed here, plus a session accessor
  for the throttle counters;
* it returns the **minimum** — a domain lookup yields the tenant id, default
  role and auto-join flag, never a tenant name, never a user, never a row from
  any other table;
* it leaks nothing the endpoint does not already leak. "Is this domain
  allowlisted?" is the answer signup gives out loud, by design.

``tests/test_pre_tenant.py`` asserts the surface stays this small; widening it
is the thing to catch in review.
"""

from __future__ import annotations

import uuid
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass

from sqlalchemy import select

from relay.domain.enums import Role
from relay.domain.residency import AllowlistedDomain
from relay.infra.db.models import TenantEmailDomain
from relay.infra.db.session import SystemSession, system_session


@dataclass(frozen=True, slots=True)
class DomainResidency:
    tenant_id: uuid.UUID
    allowlist: AllowlistedDomain


class PreTenantRepository:
    @contextmanager
    def session(self) -> Iterator[SystemSession]:
        """For the throttle counters, which live in a table with no tenant.

        Exposed rather than hidden because the limiter needs to hold a row lock
        across a read and a write; handing it a session is honest about that.
        """
        with system_session() as session:
            yield session
            session.commit()

    @staticmethod
    def resolve_domain(session: SystemSession, domain: str) -> DomainResidency | None:
        """Exact match only.

        No subdomain matching: ``evil.example.com`` matching ``example.com``
        would be one domain takeover away from an open door, and S-3 fixes
        domain ↔ tenant as one-to-one anyway.
        """
        row = session.scalars(
            select(TenantEmailDomain).where(TenantEmailDomain.domain == domain.strip().lower())
        ).first()
        if row is None:
            return None
        return DomainResidency(
            tenant_id=row.tenant_id,
            allowlist=AllowlistedDomain(
                domain=row.domain,
                default_role=Role(row.default_role),
                auto_join=row.auto_join,
            ),
        )

    @staticmethod
    def email_taken(session: SystemSession, tenant_id: uuid.UUID, email: str) -> bool:
        """Whether the address already has an account in that tenant.

        Returns a bool and nothing else on purpose — the caller must not be able
        to turn this into "tell me about that user". The signup use case is also
        careful not to *surface* the answer; see its note on enumeration.
        """
        from relay.infra.db.models import User

        return (
            session.scalars(
                select(User.id).where(User.tenant_id == tenant_id, User.email == email).limit(1)
            ).first()
            is not None
        )
