"""API-4: rotatable webhook secret version

Adds ``webhook_endpoint.secret_version``, which is how a per-endpoint signing
secret is rotated (§8.5's "secret 每端点独立，可轮换").

**Why a counter and not a stored secret.** HMAC signing needs the secret *back*,
so the obvious design stores it recoverably — and then a database dump is enough
to forge signed deliveries. Instead the secret is derived,
``HMAC(master key, "<endpoint id>:<version>")``
(``relay.app.webhooks.secret_for``): the database holds no signing material at
all, and rotation is an increment. ``secret_hash`` keeps a fingerprint of the
current secret purely so that a changed master key is *detected* rather than
showing up as every consumer's verification quietly failing.

Two notes on the generated form:

* the autogenerate diff also wanted to **drop the two pgroonga indexes** (LOG-8).
  They are created by hand in ``c4a71e9d2b18`` because SQLAlchemy cannot express
  a pgroonga operator class, so autogenerate cannot see them as belonging to the
  models and proposes removing them on every run. Those lines are deleted here.
  This is a standing hazard for the next autogenerated migration — read the diff.
* ``server_default="1"`` is present so the column can be ``NOT NULL`` on a table
  that already has rows. It is dropped immediately afterwards: leaving it would
  make the application's default (1, in the model) and the database's default two
  places to change if rotation ever starts elsewhere.

Revision ID: 66a78ea01295
Revises: c4a71e9d2b18
Create Date: 2026-08-24 19:48:24.385264

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '66a78ea01295'
down_revision: Union[str, Sequence[str], None] = 'c4a71e9d2b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'webhook_endpoint',
        sa.Column('secret_version', sa.Integer(), nullable=False, server_default='1'),
    )
    op.alter_column('webhook_endpoint', 'secret_version', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('webhook_endpoint', 'secret_version')
