"""AC-1: throttle counters for signup and verification resend

Revision ID: 89b3c3c34fdd
Revises: 90b372f0aa58
Create Date: 2026-08-23 17:58:09.317055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from relay.infra.db.rls import grant_statements


# revision identifiers, used by Alembic.
revision: str = '89b3c3c34fdd'
down_revision: Union[str, Sequence[str], None] = '90b372f0aa58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('throttle',
    sa.Column('bucket', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_throttle')),
    sa.UniqueConstraint('bucket', 'key_hash', name='uq_throttle_bucket_key_hash')
    )
    op.create_index('ix_throttle_window_started_at', 'throttle', ['window_started_at'], unique=False)
    # ### end Alembic commands ###

    # Grants but no policy: `throttle` has no tenant_id to police (a refused
    # signup has no tenant). Its protection is that it stores only digests —
    # see schema_lint.toml for the written exemption.
    for statement in grant_statements('throttle'):
        op.execute(statement)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_throttle_window_started_at', table_name='throttle')
    op.drop_table('throttle')
    # ### end Alembic commands ###
