"""MT baseline: S1 entity list, tenant_id everywhere, RLS, composite tenant FKs

The MT-1 entity list (design §4.1) as 29 tables, and the three properties that
have to be true from the first migration rather than added later:

* every table carries ``tenant_id`` (MT-2);
* every table has RLS **enabled, FORCEd, and one tenant_isolation policy**
  (MT-3) — applied at the end of ``upgrade()``, not in a follow-up migration,
  because a window where the tables exist and the policies do not is the exact
  state MT-2's lint calls more dangerous than a missing column;
* every cross-table reference is a **composite (id, tenant_id) foreign key**.
  PostgreSQL runs FK checks with policies bypassed, so a single-column FK lets
  one tenant plant a reference into another's graph — and lets that tenant's
  delete cascade back. See ``relay.infra.db.base.tenant_fk``.

MT-4's composite indexes are inline with their tables.


Revision ID: 90b372f0aa58
Revises: 
Create Date: 2026-08-23 14:13:12.663650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from relay.infra.db.rls import apply_rls
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90b372f0aa58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='tenantstatus', native_enum=False, length=32), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenant_slug'))
    )
    op.create_table('ai_context_field_config',
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('STRING', 'STRING_LIST', 'NUMBER', 'BOOLEAN', name='aicontextfieldtype', native_enum=False, length=32), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('domain_scope', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_ai_context_field_config_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_context_field_config')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_ai_context_field_config_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'field_key', name='uq_ai_context_field_config_tenant_key')
    )
    op.create_index(op.f('ix_ai_context_field_config_tenant_id'), 'ai_context_field_config', ['tenant_id'], unique=False)
    op.create_table('api_idempotency_record',
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_api_idempotency_record_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_idempotency_record')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_api_idempotency_record_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'principal_id', 'idempotency_key', name='uq_api_idempotency_record_tenant_principal_key')
    )
    op.create_index('ix_api_idempotency_record_expires_at', 'api_idempotency_record', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_idempotency_record_tenant_id'), 'api_idempotency_record', ['tenant_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.Enum('USER', 'INTEGRATION', 'SYSTEM', name='actortype', native_enum=False, length=32), nullable=False),
    sa.Column('origin', sa.Enum('WEB', 'API', 'SYSTEM', name='origin', native_enum=False, length=32), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_audit_log_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_audit_log_id_tenant_id')
    )
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_index('ix_audit_log_tenant_id_created_at', 'audit_log', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_audit_log_tenant_id_target_type_target_id', 'audit_log', ['tenant_id', 'target_type', 'target_id'], unique=False)
    op.create_table('iteration',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_iteration_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_iteration')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_iteration_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_iteration_tenant_id_name')
    )
    op.create_index(op.f('ix_iteration_tenant_id'), 'iteration', ['tenant_id'], unique=False)
    op.create_table('label',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_label_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_label')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_label_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_label_tenant_id_name')
    )
    op.create_index(op.f('ix_label_tenant_id'), 'label', ['tenant_id'], unique=False)
    op.create_table('log_template',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_log_template_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_template')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_log_template_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_log_template_tenant_id_key')
    )
    op.create_index(op.f('ix_log_template_tenant_id'), 'log_template', ['tenant_id'], unique=False)
    op.create_table('space',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_space_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_space')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_space_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_space_tenant_id_name')
    )
    op.create_index(op.f('ix_space_tenant_id'), 'space', ['tenant_id'], unique=False)
    op.create_table('tenant_email_domain',
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('default_role', sa.Enum('ADMIN', 'MEMBER', 'GUEST', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('auto_join', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_tenant_email_domain_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_email_domain')),
    sa.UniqueConstraint('domain', name='uq_tenant_email_domain_domain'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_tenant_email_domain_id_tenant_id')
    )
    op.create_index(op.f('ix_tenant_email_domain_tenant_id'), 'tenant_email_domain', ['tenant_id'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'DEACTIVATED', name='userstatus', native_enum=False, length=32), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', 'GUEST', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_user_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_user_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_id_email')
    )
    op.create_index(op.f('ix_user_tenant_id'), 'user', ['tenant_id'], unique=False)
    op.create_table('api_token',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('principal_type', sa.Enum('USER', 'SERVICE', name='principaltype', native_enum=False, length=32), nullable=False),
    sa.Column('principal_user_id', sa.Uuid(), nullable=True),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_created_by_user', ondelete='SET NULL (created_by)'),
    sa.ForeignKeyConstraint(['principal_user_id', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_principal_user_id_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_api_token_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_token')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_api_token_id_tenant_id'),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_token_token_hash'))
    )
    op.create_index(op.f('ix_api_token_tenant_id'), 'api_token', ['tenant_id'], unique=False)
    op.create_index('ix_api_token_tenant_id_revoked_at', 'api_token', ['tenant_id', 'revoked_at'], unique=False)
    op.create_table('attachment',
    sa.Column('owner_type', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('blob_key', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mime', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('scan_state', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_attachment_tenant_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_uploaded_by_user', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment')),
    sa.UniqueConstraint('blob_key', name=op.f('uq_attachment_blob_key')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_attachment_id_tenant_id')
    )
    op.create_index(op.f('ix_attachment_tenant_id'), 'attachment', ['tenant_id'], unique=False)
    op.create_table('email_verification',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_email_verification_tenant_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_email_verification_id_tenant_id'),
    sa.UniqueConstraint('token_hash', name=op.f('uq_email_verification_token_hash'))
    )
    op.create_index(op.f('ix_email_verification_tenant_id'), 'email_verification', ['tenant_id'], unique=False)
    op.create_table('identity_binding',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('WECOM', 'GITHUB', name='identityprovider', native_enum=False, length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('external_id_kind', sa.String(length=64), nullable=True),
    sa.Column('external_name', sa.String(length=255), nullable=True),
    sa.Column('bound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_identity_binding_tenant_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_binding')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_identity_binding_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'provider', 'external_id', name='uq_identity_binding_tenant_provider_ext'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'provider', name='uq_identity_binding_user_prov')
    )
    op.create_index(op.f('ix_identity_binding_tenant_id'), 'identity_binding', ['tenant_id'], unique=False)
    op.create_table('invitation',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', 'GUEST', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_invited_by_user', ondelete='SET NULL (invited_by)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_invitation_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitation')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_invitation_id_tenant_id'),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitation_token_hash'))
    )
    op.create_index(op.f('ix_invitation_tenant_id'), 'invitation', ['tenant_id'], unique=False)
    op.create_table('log',
    sa.Column('space_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('format', sa.Enum('MARKDOWN', 'PLAIN', name='logformat', native_enum=False, length=32), nullable=False),
    sa.Column('share_level', sa.Enum('PRIVATE', 'NAMED', 'SPACE', 'TENANT', name='sharelevel', native_enum=False, length=32), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('knowledge_candidate', sa.Boolean(), nullable=False),
    sa.Column('marked_by', sa.Uuid(), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_author_id_user', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['marked_by', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_marked_by_user', ondelete='SET NULL (marked_by)'),
    sa.ForeignKeyConstraint(['space_id', 'tenant_id'], ['space.id', 'space.tenant_id'], name='fk_space_id_space', ondelete='SET NULL (space_id)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_log_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_log_id_tenant_id')
    )
    op.create_index(op.f('ix_log_tenant_id'), 'log', ['tenant_id'], unique=False)
    op.create_index('ix_log_tenant_id_author_id_updated_at', 'log', ['tenant_id', 'author_id', 'updated_at'], unique=False)
    op.create_index('ix_log_tenant_id_space_id_updated_at', 'log', ['tenant_id', 'space_id', 'updated_at'], unique=False)
    op.create_table('notification',
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_recipient_id_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_notification_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_notification_id_tenant_id')
    )
    op.create_index(op.f('ix_notification_tenant_id'), 'notification', ['tenant_id'], unique=False)
    op.create_index('ix_notification_tenant_id_recipient_id_read_at', 'notification', ['tenant_id', 'recipient_id', 'read_at'], unique=False)
    op.create_table('space_member',
    sa.Column('space_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('space_role', sa.Enum('OWNER', 'MEMBER', name='spacerole', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['space_id', 'tenant_id'], ['space.id', 'space.tenant_id'], name='fk_space_id_space', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_space_member_tenant_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_space_member')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_space_member_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'space_id', 'user_id', name='uq_space_member_space_user')
    )
    op.create_index(op.f('ix_space_member_tenant_id'), 'space_member', ['tenant_id'], unique=False)
    op.create_table('ticket',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BUG', 'FEATURE', 'TASK', name='tickettype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'BLOCKED', 'WONT_FIX', name='ticketstatus', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', name='priority', native_enum=False, length=32), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('reporter_id', sa.Uuid(), nullable=True),
    sa.Column('iteration_id', sa.Uuid(), nullable=True),
    sa.Column('pr_url', sa.String(length=1024), nullable=True),
    sa.Column('ai_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('submitter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('actor_type', sa.Enum('USER', 'INTEGRATION', 'SYSTEM', name='actortype', native_enum=False, length=32), nullable=False),
    sa.Column('origin', sa.Enum('WEB', 'API', 'SYSTEM', name='origin', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_assignee_id_user', ondelete='SET NULL (assignee_id)'),
    sa.ForeignKeyConstraint(['iteration_id', 'tenant_id'], ['iteration.id', 'iteration.tenant_id'], name='fk_iteration_id_iteration', ondelete='SET NULL (iteration_id)'),
    sa.ForeignKeyConstraint(['reporter_id', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_reporter_id_user', ondelete='SET NULL (reporter_id)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_ticket_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_ticket_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'number', name='uq_ticket_tenant_id_number')
    )
    op.create_index(op.f('ix_ticket_tenant_id'), 'ticket', ['tenant_id'], unique=False)
    op.create_index('ix_ticket_tenant_id_assignee_id_status', 'ticket', ['tenant_id', 'assignee_id', 'status'], unique=False)
    op.create_index('ix_ticket_tenant_id_status_updated_at', 'ticket', ['tenant_id', 'status', 'updated_at'], unique=False)
    op.create_index('ix_ticket_tenant_id_updated_at', 'ticket', ['tenant_id', 'updated_at'], unique=False)
    op.create_table('webhook_endpoint',
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret_hash', sa.String(length=128), nullable=False),
    sa.Column('event_types', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'PAUSED', 'DISABLED', name='webhookstate', native_enum=False, length=32), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_created_by_user', ondelete='SET NULL (created_by)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_webhook_endpoint_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_endpoint')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_webhook_endpoint_id_tenant_id')
    )
    op.create_index(op.f('ix_webhook_endpoint_tenant_id'), 'webhook_endpoint', ['tenant_id'], unique=False)
    op.create_table('log_edit_lock',
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('holder_id', sa.Uuid(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['holder_id', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_holder_id_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['log_id', 'tenant_id'], ['log.id', 'log.tenant_id'], name='fk_log_id_log', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_log_edit_lock_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_edit_lock')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_log_edit_lock_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'log_id', name='uq_log_edit_lock_log')
    )
    op.create_index(op.f('ix_log_edit_lock_tenant_id'), 'log_edit_lock', ['tenant_id'], unique=False)
    op.create_table('log_share_grant',
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_granted_by_user', ondelete='SET NULL (granted_by)'),
    sa.ForeignKeyConstraint(['log_id', 'tenant_id'], ['log.id', 'log.tenant_id'], name='fk_log_id_log', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_log_share_grant_tenant_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_share_grant')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_log_share_grant_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'log_id', 'user_id', name='uq_log_share_grant_log_user')
    )
    op.create_index(op.f('ix_log_share_grant_tenant_id'), 'log_share_grant', ['tenant_id'], unique=False)
    op.create_table('log_version',
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('rolled_back_from', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_author_id_user', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['log_id', 'tenant_id'], ['log.id', 'log.tenant_id'], name='fk_log_id_log', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_log_version_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_version')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_log_version_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'log_id', 'version_no', name='uq_log_version_log_version_no')
    )
    op.create_index(op.f('ix_log_version_tenant_id'), 'log_version', ['tenant_id'], unique=False)
    op.create_table('notification_delivery',
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('INAPP', 'EMAIL', name='notificationchannel', native_enum=False, length=32), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'SENT', 'FAILED', 'SUPPRESSED', name='deliverystate', native_enum=False, length=32), nullable=False),
    sa.Column('aggregated_into', sa.Uuid(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aggregated_into', 'tenant_id'], ['notification.id', 'notification.tenant_id'], name='fk_aggregated_into_notification', ondelete='SET NULL (aggregated_into)'),
    sa.ForeignKeyConstraint(['notification_id', 'tenant_id'], ['notification.id', 'notification.tenant_id'], name='fk_notification_id_notification', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_notification_delivery_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_delivery')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_notification_delivery_id_tenant_id')
    )
    op.create_index('ix_notification_delivery_state_scheduled_at', 'notification_delivery', ['state', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_notification_delivery_tenant_id'), 'notification_delivery', ['tenant_id'], unique=False)
    op.create_table('ticket_comment',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'INTEGRATION', 'SYSTEM', name='actortype', native_enum=False, length=32), nullable=False),
    sa.Column('origin', sa.Enum('WEB', 'API', 'SYSTEM', name='origin', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_author_id_user', ondelete='SET NULL (author_id)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_ticket_comment_tenant_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id', 'tenant_id'], ['ticket.id', 'ticket.tenant_id'], name='fk_ticket_id_ticket', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_comment')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_ticket_comment_id_tenant_id')
    )
    op.create_index(op.f('ix_ticket_comment_tenant_id'), 'ticket_comment', ['tenant_id'], unique=False)
    op.create_index('ix_ticket_comment_tenant_id_ticket_id_created_at', 'ticket_comment', ['tenant_id', 'ticket_id', 'created_at'], unique=False)
    op.create_table('ticket_external_ref',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('system', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('external_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_ticket_external_ref_tenant_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id', 'tenant_id'], ['ticket.id', 'ticket.tenant_id'], name='fk_ticket_id_ticket', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_external_ref')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_ticket_external_ref_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'system', 'external_id', name='uq_ticket_external_ref_tenant_sys_ext')
    )
    op.create_index(op.f('ix_ticket_external_ref_tenant_id'), 'ticket_external_ref', ['tenant_id'], unique=False)
    op.create_table('ticket_label',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('label_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['label_id', 'tenant_id'], ['label.id', 'label.tenant_id'], name='fk_label_id_label', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_ticket_label_tenant_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id', 'tenant_id'], ['ticket.id', 'ticket.tenant_id'], name='fk_ticket_id_ticket', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_label')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_ticket_label_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'ticket_id', 'label_id', name='uq_ticket_label_ticket_label')
    )
    op.create_index(op.f('ix_ticket_label_tenant_id'), 'ticket_label', ['tenant_id'], unique=False)
    op.create_table('ticket_status_history',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'BLOCKED', 'WONT_FIX', name='ticketstatus', native_enum=False, length=32), nullable=True),
    sa.Column('to_status', sa.Enum('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'BLOCKED', 'WONT_FIX', name='ticketstatus', native_enum=False, length=32), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.Enum('USER', 'INTEGRATION', 'SYSTEM', name='actortype', native_enum=False, length=32), nullable=False),
    sa.Column('origin', sa.Enum('WEB', 'API', 'SYSTEM', name='origin', native_enum=False, length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_ticket_status_history_tenant_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id', 'tenant_id'], ['ticket.id', 'ticket.tenant_id'], name='fk_ticket_id_ticket', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_status_history')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_ticket_status_history_id_tenant_id')
    )
    op.create_index(op.f('ix_ticket_status_history_tenant_id'), 'ticket_status_history', ['tenant_id'], unique=False)
    op.create_index('ix_ticket_status_history_tenant_id_ticket_id_created_at', 'ticket_status_history', ['tenant_id', 'ticket_id', 'created_at'], unique=False)
    op.create_table('webhook_delivery',
    sa.Column('endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'IN_FLIGHT', 'DELIVERED', 'DEAD_LETTER', name='webhookdeliverystate', native_enum=False, length=32), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id', 'tenant_id'], ['webhook_endpoint.id', 'webhook_endpoint.tenant_id'], name='fk_endpoint_id_webhook_endpoint', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_webhook_delivery_tenant_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_delivery')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_webhook_delivery_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'endpoint_id', 'event_id', name='uq_webhook_delivery_endpoint_event')
    )
    op.create_index('ix_webhook_delivery_state_next_retry_at', 'webhook_delivery', ['state', 'next_retry_at'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_tenant_id'), 'webhook_delivery', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # MT-3. ENABLE + FORCE ROW LEVEL SECURITY, one uniform tenant_isolation
    # policy per table, and the grants the non-owner runtime role needs to
    # reach the tables at all.
    apply_rls(op.get_bind())



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_delivery_tenant_id'), table_name='webhook_delivery')
    op.drop_index('ix_webhook_delivery_state_next_retry_at', table_name='webhook_delivery')
    op.drop_table('webhook_delivery')
    op.drop_index('ix_ticket_status_history_tenant_id_ticket_id_created_at', table_name='ticket_status_history')
    op.drop_index(op.f('ix_ticket_status_history_tenant_id'), table_name='ticket_status_history')
    op.drop_table('ticket_status_history')
    op.drop_index(op.f('ix_ticket_label_tenant_id'), table_name='ticket_label')
    op.drop_table('ticket_label')
    op.drop_index(op.f('ix_ticket_external_ref_tenant_id'), table_name='ticket_external_ref')
    op.drop_table('ticket_external_ref')
    op.drop_index('ix_ticket_comment_tenant_id_ticket_id_created_at', table_name='ticket_comment')
    op.drop_index(op.f('ix_ticket_comment_tenant_id'), table_name='ticket_comment')
    op.drop_table('ticket_comment')
    op.drop_index(op.f('ix_notification_delivery_tenant_id'), table_name='notification_delivery')
    op.drop_index('ix_notification_delivery_state_scheduled_at', table_name='notification_delivery')
    op.drop_table('notification_delivery')
    op.drop_index(op.f('ix_log_version_tenant_id'), table_name='log_version')
    op.drop_table('log_version')
    op.drop_index(op.f('ix_log_share_grant_tenant_id'), table_name='log_share_grant')
    op.drop_table('log_share_grant')
    op.drop_index(op.f('ix_log_edit_lock_tenant_id'), table_name='log_edit_lock')
    op.drop_table('log_edit_lock')
    op.drop_index(op.f('ix_webhook_endpoint_tenant_id'), table_name='webhook_endpoint')
    op.drop_table('webhook_endpoint')
    op.drop_index('ix_ticket_tenant_id_updated_at', table_name='ticket')
    op.drop_index('ix_ticket_tenant_id_status_updated_at', table_name='ticket')
    op.drop_index('ix_ticket_tenant_id_assignee_id_status', table_name='ticket')
    op.drop_index(op.f('ix_ticket_tenant_id'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_index(op.f('ix_space_member_tenant_id'), table_name='space_member')
    op.drop_table('space_member')
    op.drop_index('ix_notification_tenant_id_recipient_id_read_at', table_name='notification')
    op.drop_index(op.f('ix_notification_tenant_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index('ix_log_tenant_id_space_id_updated_at', table_name='log')
    op.drop_index('ix_log_tenant_id_author_id_updated_at', table_name='log')
    op.drop_index(op.f('ix_log_tenant_id'), table_name='log')
    op.drop_table('log')
    op.drop_index(op.f('ix_invitation_tenant_id'), table_name='invitation')
    op.drop_table('invitation')
    op.drop_index(op.f('ix_identity_binding_tenant_id'), table_name='identity_binding')
    op.drop_table('identity_binding')
    op.drop_index(op.f('ix_email_verification_tenant_id'), table_name='email_verification')
    op.drop_table('email_verification')
    op.drop_index(op.f('ix_attachment_tenant_id'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_index('ix_api_token_tenant_id_revoked_at', table_name='api_token')
    op.drop_index(op.f('ix_api_token_tenant_id'), table_name='api_token')
    op.drop_table('api_token')
    op.drop_index(op.f('ix_user_tenant_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tenant_email_domain_tenant_id'), table_name='tenant_email_domain')
    op.drop_table('tenant_email_domain')
    op.drop_index(op.f('ix_space_tenant_id'), table_name='space')
    op.drop_table('space')
    op.drop_index(op.f('ix_log_template_tenant_id'), table_name='log_template')
    op.drop_table('log_template')
    op.drop_index(op.f('ix_label_tenant_id'), table_name='label')
    op.drop_table('label')
    op.drop_index(op.f('ix_iteration_tenant_id'), table_name='iteration')
    op.drop_table('iteration')
    op.drop_index('ix_audit_log_tenant_id_target_type_target_id', table_name='audit_log')
    op.drop_index('ix_audit_log_tenant_id_created_at', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_api_idempotency_record_tenant_id'), table_name='api_idempotency_record')
    op.drop_index('ix_api_idempotency_record_expires_at', table_name='api_idempotency_record')
    op.drop_table('api_idempotency_record')
    op.drop_index(op.f('ix_ai_context_field_config_tenant_id'), table_name='ai_context_field_config')
    op.drop_table('ai_context_field_config')
    op.drop_table('tenant')
    # ### end Alembic commands ###
