"""AC-2: server-side login sessions

Revision ID: adf0bf9fb090
Revises: 89b3c3c34fdd
Create Date: 2026-08-23 18:13:53.273463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from relay.infra.db.rls import apply_rls


# revision identifiers, used by Alembic.
revision: str = 'adf0bf9fb090'
down_revision: Union[str, Sequence[str], None] = '89b3c3c34fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_session',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('mfa_satisfied', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_user_session_tenant_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'tenant_id'], ['user.id', 'user.tenant_id'], name='fk_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_session')),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_user_session_id_tenant_id'),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_session_token_hash'))
    )
    op.create_index(op.f('ix_user_session_tenant_id'), 'user_session', ['tenant_id'], unique=False)
    op.create_index('ix_user_session_tenant_id_user_id_created_at', 'user_session', ['tenant_id', 'user_id', 'created_at'], unique=False)
    op.create_index('ix_user_session_tenant_id_user_id_revoked_at', 'user_session', ['tenant_id', 'user_id', 'revoked_at'], unique=False)
    # ### end Alembic commands ###

    # Tenant-scoped, so it gets the policy and the grants like every other
    # table. Named explicitly rather than read from live metadata — see the
    # baseline migration for why.
    apply_rls(op.get_bind(), ['user_session'])



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_session_tenant_id_user_id_revoked_at', table_name='user_session')
    op.drop_index('ix_user_session_tenant_id_user_id_created_at', table_name='user_session')
    op.drop_index(op.f('ix_user_session_tenant_id'), table_name='user_session')
    op.drop_table('user_session')
    # ### end Alembic commands ###
