"""LOG-8: pgroonga full-text indexes over logs and ticket titles

Revision ID: c4a71e9d2b18
Revises: adf0bf9fb090
Create Date: 2026-08-24 11:05:00.000000

Hand-written rather than autogenerated: alembic does not model a pgroonga index,
and `--autogenerate` would try to drop these on the next run if they were
declared in the models. Declaring them only here keeps the model metadata
honest about what SQLAlchemy understands.

Coverage is §6.4's: **log titles + log bodies + ticket titles.** Ticket
*descriptions* are deliberately out — §6.4 lists titles for tickets, and a
description index would double the index size for the half of the corpus that is
mostly stack traces and pasted logs.

pgroonga is not a trusted extension, so it is installed by a superuser outside
the migration chain (`scripts/bootstrap_extensions.sql`, gated by
`test_pgroonga_is_provisioned`). This migration therefore assumes it exists and
says so loudly if it does not — the alternative, `CREATE EXTENSION IF NOT
EXISTS`, would fail here as `relay_owner` with a permission error that names
nothing useful.
"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4a71e9d2b18"
down_revision: Union[str, Sequence[str], None] = "adf0bf9fb090"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    installed = bind.execute(
        sa.text("SELECT count(*) FROM pg_extension WHERE extname = 'pgroonga'")
    ).scalar()
    if not installed:
        raise RuntimeError(
            "pgroonga is not installed in this database, and LOG-8 needs it. It is "
            "not a trusted extension, so a superuser has to create it:\n"
            "    sudo -u postgres psql -d <db> -f scripts/bootstrap_extensions.sql"
        )

    # One multi-column index per table. pgroonga serves `title &@ …` and
    # `body &@ …` from the same index, so this is one object to maintain rather
    # than two, and the planner can still use it for either column alone.
    op.execute("CREATE INDEX ix_log_pgroonga ON log USING pgroonga (title, body)")
    op.execute("CREATE INDEX ix_ticket_pgroonga ON ticket USING pgroonga (title)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_ticket_pgroonga")
    op.execute("DROP INDEX IF EXISTS ix_log_pgroonga")
