"""Generate the MT-1 entity registry from the models.

Direction of truth, deliberately: the models are authoritative and the document
is generated. The same inversion API-5 hits with FastAPI's OpenAPI output — a
gate that asks "does the document agree with the code?" can never fire if the
document is written by hand and nobody updates it.

So the registry is a **snapshot**: CI regenerates it and diffs. Any difference
fails until a human updates the snapshot in the PR, which is what makes a new
table visible in review rather than merely present.

    uv run python scripts/gen_entity_registry.py          # write
    uv run python scripts/gen_entity_registry.py --check  # diff only
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

from relay.infra.db.models import RESERVED_TABLE_NAMES, Base

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "markdown" / "relay-s1-entities.md"
LINT_CONFIG = ROOT / "schema_lint.toml"

HEADER = """<!-- Generated by scripts/gen_entity_registry.py. Do not edit by hand. -->

# Relay · S1 entity registry (MT-1)

Generated from `relay.infra.db.models`. The models are the source of truth; this
file is a snapshot that CI diffs, so adding a table shows up in review.

Narrative and rationale live in
[relay-s1-design.md §4.1](relay-s1-design.md#41-实体清单mt-1-产出物s1-版).
Exemptions and their written reasons live in `schema_lint.toml`.

**Every table below carries `tenant_id` and a `tenant_isolation` RLS policy**,
except where the exemption column says otherwise.
"""


def _render() -> str:
    exemptions = {}
    with LINT_CONFIG.open("rb") as fh:
        for entry in tomllib.load(fh).get("exemption", []):
            exemptions[entry["table"]] = entry

    lines = [HEADER, "", f"## Tables ({len(Base.metadata.tables)})", ""]
    lines.append("| Table | `tenant_id` | RLS policy | Tenant-scoped FKs |")
    lines.append("|---|---|---|---|")
    for name in sorted(Base.metadata.tables):
        table = Base.metadata.tables[name]
        entry = exemptions.get(name, {})
        # First line of the written reason: enough to see why, in the table.
        reason = entry.get("reason", "").strip().splitlines()
        has_tid = "✅" if "tenant_id" in table.c else f"exempt — {reason[0] if reason else '?'}"
        policy = "✅" if entry.get("requires_policy", True) else "exempt"
        fks = sorted(
            f"`{sorted(c.name for c in fk.columns if c.name != 'tenant_id')[0]}`"
            f" → `{fk.referred_table.name}`"
            for fk in table.foreign_key_constraints
            if {c.name for c in fk.columns} != {"tenant_id"}
        )
        lines.append(f"| `{name}` | {has_tid} | {policy} | {', '.join(fks) or '—'} |")

    lines += [
        "",
        "## Reserved, deliberately not created in S1",
        "",
        "Names claimed so a later phase completes a plan instead of inventing one.",
        "",
    ]
    for name in sorted(RESERVED_TABLE_NAMES):
        lines.append(f"- `{name}`")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rendered = _render()
    if not args.check:
        OUTPUT.write_text(rendered)
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
        return 0

    current = OUTPUT.read_text() if OUTPUT.exists() else ""
    if current != rendered:
        print(
            "entity registry is stale. Run:\n"
            "    uv run python scripts/gen_entity_registry.py\n"
            "and commit the result, so the new table is visible in review.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
